# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Bicep Container Registry in Azure
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: serviceConnectionName
    displayName: serviceConnectionName
    type: string
    default: yourserviceConnectionName
  - name: registryName
    displayName: Container Registry Name
    type: string
    default: yourContainerRegistry
  - name: resourceGroupName
    displayName: Resource Group Name
    type: string
    default: yourResourceGroup
  - name: location
    displayName: Location
    type: string
    default: 'eastus'

jobs:
- deployment: CreateInfra
  displayName: Initialize Create Infra
  environment: 'DEV'

- job: CreateInfraJob
  displayName: Create Infrastructure
  variables:
    - name: templateFile
      value: './Labs/bicep/07_Bicep_Registries/containerregistry.bicep'

  steps:
  - bash: |
      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
    displayName: 'Create Variables'

  - bash: |
      echo "registryName=$(registryName)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "serviceConnectionName=$(serviceConnectionName)"
      echo "templateFile=$(templateFile)"
      echo "runDateTime=$(runDateTime)"
      tree $(Pipeline.Workspace)
    displayName: 'Display Variables'
    continueOnError: true

  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group create --name $(resourceGroupName) --location $(location)

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      overrideParameters: >
        -registryName $(registryName) 
        -location $(location) 
        -runDateTime $(runDateTime)
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(serviceConnectionName)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      templateLocation: 'Linked artifact'
      deploymentMode: 'Incremental'
