variables:
  - name: azureResourceManagerConnection
    value: 'Demo Service Connection'
  - name: location
    value: 'eastus'
  - name: bicepFile
    value: 'infra/main.bicep'
  - name: bicepParameterFile
    value: 'infra/main.bicepparam'
stages:
- stage: BicepDeployDev
  jobs:
  - deployment: DeployBicepInfra
    environment: 'dev'
  - job: DeployBicep
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          azureResourceManagerConnection: $(azureServiceConnection)
          resourceGroupName: 'rg_demo_dev'
          location: $(location)
          csmFile: $(bicepFile)
          csmParametersFile: $(bicepParameterFile)
- stage: BicepDeployProd
  dependsOn: AppDeployDev
  condition: succeeded('AppDeployDev')
  jobs:
  - deployment: DeployBicepInfra
    environment: 'prod'
  - job: DeployBicep
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          azureResourceManagerConnection: $(azureServiceConnection)
          resourceGroupName: 'rg_demo_prod'
          location: $(location)
          csmFile: $(bicepFile)
          csmParametersFile: $(bicepParameterFile)
