trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BicepDeployDev
  jobs:
  - template: templates/deploy-bicep-template.yml
    parameters:
      environmentName: 'dev'
      bicepFile: $(bicepFile)
      parameterFile: $(bicepParameterFile)

- stage: BicepDeployQA
  dependsOn: AppDeployDev
  condition: succeeded('AppDeployDev')
  jobs:
  - template: templates/deploy-bicep-template.yml
    parameters:
      environmentName: 'qa'
      bicepFile: $(bicepFile)
      parameterFile: $(bicepParameterFile)

- stage: BicepDeployProd
  dependsOn: AppDeployQA
  condition: succeeded('AppDeployQA')
  jobs:
  - template: templates/deploy-bicep-template.yml
    parameters:
      environmentName: 'prod'
      bicepFile: $(bicepFile)
      parameterFile: $(bicepParameterFile)

