# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# See readme file for info about the contents of the variable group
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: deployToEnvironment
    displayName: Deploy To
    type: string
    values:
      - DEV
      - QA
      - PROD
      - DEV-QA-PROD
    default: DEV

variables:
  - group: DurableDemo
  # you have to have this in here so it resolves at YML compile time
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if ne(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
  - template: templates/98-infra-only-pipe.yml
    parameters:
      environments: ['${{ parameters.deployToEnvironment }}']
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
      singleEnvironment: 'true'

- ${{ if eq(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
  - template: templates/98-infra-only-pipe.yml
    parameters:
      environments: ['DEV','QA','PROD']
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}