name: scan-pipeline

trigger:
 - none
# schedules:
# - cron: '0 12 * * 3'
#   displayName: Scan Every Wednesday
#   branches:
#     include:
#     - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: ScanApplication
  jobs:
  - template: /.azdo/pipelines/templates/scan-code-template.yml
