# ----------------------------------------------------------------------------------------------------
# Pipeline to run a Terraform Init and Plan
# ----------------------------------------------------------------------------------------------------
# This pipeline uses a template that expects variables in a variable group - see template for details!
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: ubuntu-latest

trigger: none

# ----------------------------------------------------------------------------------------------------
parameters:
- name: deployToEnvironment
  displayName: Deploy To Environment
  type: string
  values:
    - dev
    - prod
  default: dev

# ----------------------------------------------------------------------------------------------------
resources:
  pipelines:
  - pipeline: terraform.plan.pipeline  # internal identifier for the resource
    source: 12-terraform-plan-pipeline  # name of the pipeline that produces an artifact
    branch: main                       # should only allow builds from the main branch to be used

# ----------------------------------------------------------------------------------------------------
variables:
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
jobs:
- template: ./templates/jobs/tf-apply-template.yml
  parameters:
    env: ${{ parameters.deployToEnvironment }}
    pipelineResourceIdentifier: 'terraform.plan.pipeline'
    serviceConnectionName: $(serviceConnectionName)
