### ---------------------------------------------------------------------------
### DotNet WebApp API Test Harness
### ---------------------------------------------------------------------------

### Change this to match your Azure WebApp URL
@baseUrl = https://web-glaxjsvr3ts7y.azurewebsites.net/api
@APIKey=secret

### ---------------------------------------------------------------------------
### Retrieve a Joke
### ---------------------------------------------------------------------------
GET {{baseUrl}}/joke
APIKey: {{APIKey}}

