### ---------------------------------------------------------------------------
### Python Function Test Harness
### ---------------------------------------------------------------------------

### Change this to match your Azure Function URL
@baseUrl = https://pyfunc-glaxjsvr3ts7y.azurewebsites.net/api

### ---------------------------------------------------------------------------
### Nobody Test
### ---------------------------------------------------------------------------
GET {{baseUrl}}/EchoTrigger

### ---------------------------------------------------------------------------
### Body Test
### ---------------------------------------------------------------------------
POST {{baseUrl}}/EchoTrigger
content-type: text/json

{ "name": "Lyle" }
