# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to scan files for security issues
# ------------------------------------------------------------------------------------------------------------------------
# NOTE: If you get the error: 'Resource not accessible by integration' on the upload step
# then you will need to go into the Repository -> Settings -> Workflow Permissions
# and enable the "Read and write permissions" to be able to publish the results
# ------------------------------------------------------------------------------------------------------------------------
name: template_security_scan
run-name: Run Security Scan
on:
  workflow_call:
    inputs:
      continueOnScanError:
        required: false
        default: true
        type: boolean
  
# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scanner:
    name: Security Scan
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          8.0.x

    - name: Run Full Infra Scan
      continue-on-error: ${{ inputs.continueOnScanError }} 
      uses: microsoft/security-devops-action@latest
      id: msdo
      with:
        tools: templateanalyzer,terrascan,trivy

    - name: Upload MS SecDevOps alerts to Security tab
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}

    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      uses: actions/upload-artifact@v4
      with:  
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
