# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to run a Playwright Test
# ------------------------------------------------------------------------------------------------------------------------
name: z_template_webapp_test
run-name: Run Smoke Test

on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string
      # testConfig:
      #   required: true
      #   type: string
      # testPath:
      #   required: true
      #   type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Display Variables
      run: |-
        echo "envCode=${{ inputs.envCode }}"
        echo "Files in ${{ env.GITHUB_ACTION_PATH }}"
        tree ${{ env.GITHUB_ACTION_PATH }}
      continue-on-error: true

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

      #run: npx playwright test ${{ inputs.testPath }} --config ${{ inputs.testConfig }}
     
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
