# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy an already built Function App to Azure
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: z_template_python_function_deploy
run-name: Deploy Function App
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string
      functionName:
        required: false
        type: string
        default: 'process'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ inputs.envCode }}

    env:
      artifactName: pythonapp
      generatedAppEnvName: 'pyfunc-${{ vars.RESOURCE_TOKEN }}'

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.artifactName }}

    - name: List Files
      run: 
        tree ${{ env.GITHUB_ACTION_PATH }}
      continue-on-error: true

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      # - name: Azure login
      #   uses: wlgore/azure-repository-login@v1
      #   id: azure-login
      #   with:
      #     azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}  # this is created by the action - the first time it fails, run again and it works
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}                   # need to set this manually
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}                               # need to set this manually
      #     bot-credentials: ${{ secrets.AZURE_REPOSITORY_LOGIN_BOT_CREDENTIALS }}  # org level creds should exist already
      #     environment: ${{ inputs.environment }}
      #     location: EastUS
      #     use-pretty-names: true

    - name: Deploy package to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.generatedAppEnvName }}
        package: .

    - name: Logout and cleanup
      shell: bash
      run: |
        az logout
        az cache purge
        az account clear
